#Basic maths in NumPy

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
print("1D: ", arr)
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D: ", arr1)

1D:  [1 2 3]
2D:  [[1 2 3]
 [4 5 6]]


In [ ]:
z = np.zeros((3, 3))
print(z)
o = np.ones((2, 2))
print(o)
r = np.arange(0, 10, 2)
print(r)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]


In [35]:
r = np.arange(1, 10)
s = np.arange(10, 19)
print(r,s)
print(r.shape)
print(r.ndim)
print(r.dtype)
print(np.min(r))

[1 2 3 4 5 6 7 8 9] [10 11 12 13 14 15 16 17 18]
(9,)
1
int64
1


In [36]:
print("3 x 3...")
r = r.reshape(3, 3)
s = s.reshape(3, 3)
print(r)
print("Flattern...")
r = r.flatten()
print(r)
print("Transpose...")
print(s)
print(s.T)

3 x 3...
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattern...
[1 2 3 4 5 6 7 8 9]
Transpose...
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[10 13 16]
 [11 14 17]
 [12 15 18]]


## Random

In [41]:

x = np.random.rand(10)*100
print(x)
print(np.floor(x))
print(np.ceil(x))

[15.0939689  49.79144201 11.68442621 70.33094244 79.06424952 89.51686861
  2.04099993 74.53934779 62.00324702 33.92722316]
[15. 49. 11. 70. 79. 89.  2. 74. 62. 33.]
[16. 50. 12. 71. 80. 90.  3. 75. 63. 34.]
