#Splitting

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn


d1 = pd.read_csv("/content/drive/MyDrive/Data.csv")

la = sklearn.preprocessing.LabelEncoder()
d1["State"] = la.fit_transform(d1["State"])
d1

R&D Spend  Administration  Marketing Spend  State     Profit
0   165349.20       136897.80        471784.10      2  192261.83
1   162597.70       151377.59        443898.53      0  191792.06
2   153441.51       101145.55        407934.54      1  191050.39
3   144372.41       118671.85        383199.62      2  182901.99
4   142107.34        91391.77        366168.42      1  166187.94
5   131876.90        99814.71        362861.36      2  156991.12
6   134615.46       147198.87        127716.82      0  156122.51
7   130298.13       145530.06        323876.68      1  155752.60
8   120542.52       148718.95        311613.29      2  152211.77
9   123334.88       108679.17        304981.62      0  149759.96
10  101913.08       110594.11        229160.95      1  146121.95
11  100671.96        91790.61        249744.55      0  144259.40
12   93863.75       127320.38        249839.44      1  141585.52
13   91992.39       135495.07        252664.93      0  134307.35
14  119943.24       156547.42        256512.92      1  132602.65
15  114523.61       122616.84        261776.23      2  129917.04
16   78013.11       121597.55        264346.06      0  126992.93
17   94657.16       145077.58        282574.31      2  125370.37
18   91749.16       114175.79        294919.57      1  124266.90
19   86419.70       153514.11             0.00      2  122776.86
20   76253.86       113867.30        298664.47      0  118474.03
21   78389.47       153773.43        299737.29      2  111313.02
22   73994.56       122782.75        303319.26      1  110352.25
23   67532.53       105751.03        304768.73      1  108733.99
24   77044.01        99281.34        140574.81      2  108552.04
25   64664.71       139553.16        137962.62      0  107404.34
26   75328.87       144135.98        134050.07      1  105733.54
27   72107.60       127864.55        353183.81      2  105008.31
28   66051.52       182645.56        118148.20      1  103282.38
29   65605.48       153032.06        107138.38      2  101004.64
30   61994.48       115641.28         91131.24      1   99937.59
31   61136.38       152701.92         88218.23      2   97483.56
32   63408.86       129219.61         46085.25      0   97427.84
33   55493.95       103057.49        214634.81      1   96778.92
34   46426.07       157693.92        210797.67      0   96712.80
35   46014.02        85047.44        205517.64      2   96479.51
36   28663.76       127056.21        201126.82      1   90708.19
37   44069.95        51283.14        197029.42      0   89949.14
38   20229.59        65947.93        185265.10      2   81229.06
39   38558.51        82982.09        174999.30      0   81005.76
40   28754.33       118546.05        172795.67      0   78239.91
41   27892.92        84710.77        164470.71      1   77798.83
42   23640.93        96189.63        148001.11      0   71498.49
43   15505.73       127382.30         35534.17      2   69758.98
44   22177.74       154806.14         28334.72      0   65200.33
45    1000.23       124153.04          1903.93      2   64926.08
46    1315.46       115816.21        297114.46      1   49490.75
47       0.00       135426.92             0.00      0   42559.73
48     542.05        51743.15             0.00      2   35673.41
49       0.00       116983.80         45173.06      0   14681.40

In [11]:
x = d1.drop('Profit', axis = 1)
y = d1['Profit']
x

R&D Spend  Administration  Marketing Spend  State
0   165349.20       136897.80        471784.10      2
1   162597.70       151377.59        443898.53      0
2   153441.51       101145.55        407934.54      1
3   144372.41       118671.85        383199.62      2
4   142107.34        91391.77        366168.42      1
5   131876.90        99814.71        362861.36      2
6   134615.46       147198.87        127716.82      0
7   130298.13       145530.06        323876.68      1
8   120542.52       148718.95        311613.29      2
9   123334.88       108679.17        304981.62      0
10  101913.08       110594.11        229160.95      1
11  100671.96        91790.61        249744.55      0
12   93863.75       127320.38        249839.44      1
13   91992.39       135495.07        252664.93      0
14  119943.24       156547.42        256512.92      1
15  114523.61       122616.84        261776.23      2
16   78013.11       121597.55        264346.06      0
17   94657.16       145077.58        282574.31      2
18   91749.16       114175.79        294919.57      1
19   86419.70       153514.11             0.00      2
20   76253.86       113867.30        298664.47      0
21   78389.47       153773.43        299737.29      2
22   73994.56       122782.75        303319.26      1
23   67532.53       105751.03        304768.73      1
24   77044.01        99281.34        140574.81      2
25   64664.71       139553.16        137962.62      0
26   75328.87       144135.98        134050.07      1
27   72107.60       127864.55        353183.81      2
28   66051.52       182645.56        118148.20      1
29   65605.48       153032.06        107138.38      2
30   61994.48       115641.28         91131.24      1
31   61136.38       152701.92         88218.23      2
32   63408.86       129219.61         46085.25      0
33   55493.95       103057.49        214634.81      1
34   46426.07       157693.92        210797.67      0
35   46014.02        85047.44        205517.64      2
36   28663.76       127056.21        201126.82      1
37   44069.95        51283.14        197029.42      0
38   20229.59        65947.93        185265.10      2
39   38558.51        82982.09        174999.30      0
40   28754.33       118546.05        172795.67      0
41   27892.92        84710.77        164470.71      1
42   23640.93        96189.63        148001.11      0
43   15505.73       127382.30         35534.17      2
44   22177.74       154806.14         28334.72      0
45    1000.23       124153.04          1903.93      2
46    1315.46       115816.21        297114.46      1
47       0.00       135426.92             0.00      0
48     542.05        51743.15             0.00      2
49       0.00       116983.80         45173.06      0

In [20]:
test = sklearn.model_selection.train_test_split
x_train, x_test, y_train, y_test = test(x, y, test_size = 0.2, random_state= 42)
print(x_train)
print('\n')
print(x_test)
print('\n')
print(y_train)
print('\n')
print(y_test)
print('\n')

    R&D Spend  Administration  Marketing Spend  State
24   77044.01        99281.34        140574.81      2
25   64664.71       139553.16        137962.62      0
29   65605.48       153032.06        107138.38      2
3   144372.41       118671.85        383199.62      2
43   15505.73       127382.30         35534.17      2
2   153441.51       101145.55        407934.54      1
10  101913.08       110594.11        229160.95      1
11  100671.96        91790.61        249744.55      0
6   134615.46       147198.87        127716.82      0
23   67532.53       105751.03        304768.73      1
38   20229.59        65947.93        185265.10      2
28   66051.52       182645.56        118148.20      1
45    1000.23       124153.04          1903.93      2
8   120542.52       148718.95        311613.29      2
30   61994.48       115641.28         91131.24      1
41   27892.92        84710.77        164470.71      1
44   22177.74       154806.14         28334.72      0
49       0.00       116983.8

#FE & Scaling

In [25]:
poly = sklearn.preprocessing.PolynomialFeatures(degree = 2)
x1 = [[2], [3]]
poly.fit(x1)
xp = poly.transform(x1)
xp

array([[1., 2., 4.],
       [1., 3., 9.]])

In [26]:
poly = sklearn.preprocessing.PolynomialFeatures(degree = 2)
x1 = [[2], [3]]
poly.fit(x_test)
xp = poly.transform(x_test)
xp

array([[1.00000000e+00, 4.60140200e+04, 8.50474400e+04, 2.05517640e+05,
        2.00000000e+00, 2.11729004e+09, 3.91337461e+09, 9.45669280e+09,
        9.20280400e+04, 7.23306705e+09, 1.74787492e+10, 1.70094880e+05,
        4.22375004e+10, 4.11035280e+05, 4.00000000e+00],
       [1.00000000e+00, 2.87543300e+04, 1.18546050e+05, 1.72795670e+05,
        0.00000000e+00, 8.26811494e+08, 3.40871224e+09, 4.96862372e+09,
        0.00000000e+00, 1.40531660e+10, 2.04842441e+10, 0.00000000e+00,
        2.98583436e+10, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 1.35426920e+05, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.83404507e+10, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.42107340e+05, 9.13917700e+04, 3.66168420e+05,
        1.00000000e+00, 2.01944961e+10, 1.29874413e+10, 5.20352202e+10,
        1.42107340e+05, 8.35245562e+0

##Standardization & Normalization

In [33]:
df = pd.DataFrame({"Age": [25, 30, 35,40,45,50], "Salary":[25000, 30000, 35000,40000,45000,50000] })
sc = sklearn.preprocessing.StandardScaler()
sc.fit(df)
df_s = sc.transform(df)
print(df)
print('\n')
print(df_s)

sc = sklearn.preprocessing.MinMaxScaler()
sc.fit(df)
df_n = sc.transform(df)
print('\n')
print(df_n)

   Age  Salary
0   25   25000
1   30   30000
2   35   35000
3   40   40000
4   45   45000
5   50   50000


[[-1.46385011 -1.46385011]
 [-0.87831007 -0.87831007]
 [-0.29277002 -0.29277002]
 [ 0.29277002  0.29277002]
 [ 0.87831007  0.87831007]
 [ 1.46385011  1.46385011]]


[[0.  0. ]
 [0.2 0.2]
 [0.4 0.4]
 [0.6 0.6]
 [0.8 0.8]
 [1.  1. ]]


## P C A

In [34]:

# dimensionality Reduction
X2=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7],[5,6,7,8],[6,7,8,9]])
Y2=np.array([1,2,3,4,5,6])
from sklearn.decomposition import PCA
sc = sklearn.preprocessing.StandardScaler()
X2=sc.fit_transform(X2)
pca=PCA(n_components=2)
pca.fit(X2)
X_pca=pca.transform(X2)
print(X_pca)#

[[-2.92770022e+00 -9.77627268e-16]
 [-1.75662013e+00 -5.59679545e-16]
 [-5.85540044e-01 -1.95096073e-16]
 [ 5.85540044e-01  1.95096073e-16]
 [ 1.75662013e+00  5.59679545e-16]
 [ 2.92770022e+00  9.77627268e-16]]


## S V D

In [35]:
X=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7],[5,6,7,8],[6,7,8,9]])
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=2)
svd.fit(X)
Xs = svd.transform(X)
print(Xs)

[[ 5.34276846 -1.20616134]
 [ 7.3034952  -0.81176223]
 [ 9.26422193 -0.41736311]
 [11.22494867 -0.02296399]
 [13.18567541  0.37143512]
 [15.14640214  0.76583424]]


In [36]:
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import numpy as np

X2 = np.array([[1,2,3,4],
               [2,3,4,5],
               [3,4,5,6],
               [4,5,6,7],
               [5,6,7,8],
               [6,7,8,9]])

Y = np.array([1, 1, 2, 2, 3, 3])  # Only 3 classes

sc = StandardScaler()
X2 = sc.fit_transform(X2)

lda = LinearDiscriminantAnalysis(n_components=2)
lda.fit(X2, Y)
X_lda = lda.transform(X2)

print(X_lda)

[[-3.53553391]
 [-2.12132034]
 [-0.70710678]
 [ 0.70710678]
 [ 2.12132034]
 [ 3.53553391]]


##Feature Selection

In [37]:

data={
    'A':[1,2,3,4,5],
    'B':[1,2,3,4,5],
    'C':[1,2,3,4,5]
}
df=pd.DataFrame(data)
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=1)
df=vt.fit_transform(df)
df

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [38]:
#Feature Selection: Elimination
#Variance threshold
data={
    'A':[0,0,0,0,0],
    'B':[1,2,3,4,5],
    'C':[10,10,10,10,10]
}
df=pd.DataFrame(data)
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=1)
vt.fit(df)
df=vt.transform(df)
df

array([[1],
       [2],
       [3],
       [4],
       [5]])

##Data Imbalance Handling